name: Docker image build.

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 */7 * *"
  push:
    paths-ignore:
    - '**.md'
    branches:
      - "master"
      - "main"

jobs:
  prepare:
    name: Preparing build context
    runs-on: ubuntu-latest
    outputs:
      SANITISED_REPOSITORY_NAME: ${{ steps.get_env.outputs.SANITISED_REPOSITORY_NAME }}
      DOCKER_IMAGE: ${{ steps.get_env.outputs.DOCKER_IMAGE }}
      KUSTOMIZE_VERSION: ${{ steps.get_env.outputs.KUSTOMIZE_VERSION }}
      KUBECTL_VERSION: ${{ steps.get_env.outputs.KUBECTL_VERSION }}
      DOCKER_IMAGE_SEMVER: ${{ steps.semver.outputs.semantic_version }}
      HELM_VERSION: ${{ steps.get_env.outputs.HELM_VERSION }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Setting environment variables
        id: get_env
        run: |
          TMP_SANITISED_REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY | sed -e 's|\.|-|g')
          echo "SANITISED_REPOSITORY_NAME=$TMP_SANITISED_REPOSITORY_NAME" >> $GITHUB_OUTPUT
          echo "DOCKER_IMAGE=ghcr.io/${{ github.repository_owner }}/$TMP_SANITISED_REPOSITORY_NAME" >> $GITHUB_OUTPUT
          KUSTOMIZE_VERSION=$(curl --silent "https://api.github.com/repos/kubernetes-sigs/kustomize/releases" | grep '"tag_name": "kustomize/' | head -n 1 | sed -E 's/.*"([^"]+)".*/\1/' | sed -E 's/kustomize\///')
          echo "KUSTOMIZE_VERSION=$KUSTOMIZE_VERSION" >> $GITHUB_OUTPUT
          KUBECTL_VERSION=$(curl -L -s  https://dl.k8s.io/release/stable.txt)
          echo "KUBECTL_VERSION=$KUBECTL_VERSION" >> $GITHUB_OUTPUT
          HELM_VERSION=$(curl --silent "https://api.github.com/repos/helm/helm/releases" | grep -ve "-rc" | grep '"tag_name": ' |  head -n 1 | sed -E 's/.*"([^"]+)".*/\1/' | sed -E 's/^v//g')
          echo "HELM_VERSION=$HELM_VERSION" >> $GITHUB_OUTPUT
      - name: Establish semver
        id: semver
        uses: lukaszraczylo/semver-generator@v1
        with:
          config_file: semver.yaml
          repository_local: true
          github_username: $GHCR_TOKEN_USER
          github_token: ${{ secrets.ghcr-token }}
      - name: Semver check
        run: |
          echo "Semantic version detected: ${{ steps.semver.outputs.semantic_version }}"

  build:
    needs: [ prepare ]
    name: Docker image build (multiarch)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.ACTOR }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Prepare for push
        id: prep
        run: |
          TAGS="${{ needs.prepare.outputs.DOCKER_IMAGE }}:${{ needs.prepare.outputs.DOCKER_IMAGE_SEMVER }},${{ needs.prepare.outputs.DOCKER_IMAGE }}:latest,${{ needs.prepare.outputs.DOCKER_IMAGE }}:kubectl-${{ needs.prepare.outputs.KUBECTL_VERSION }},${{ needs.prepare.outputs.DOCKER_IMAGE }}:kustomize-${{ needs.prepare.outputs.KUSTOMIZE_VERSION }},${{ needs.prepare.outputs.DOCKER_IMAGE }}:helm-${{ needs.prepare.outputs.HELM_VERSION }},${{ needs.prepare.outputs.DOCKER_IMAGE }}:$GITHUB_RUN_NUMBER"
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          LABELS="org.opencontainers.image.revision=${{ needs.prepare.outputs.DOCKER_IMAGE_SEMVER }}"
          LABELS="$LABELS,org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          LABELS="$LABELS,org.opencontainers.image.version=${{ needs.prepare.outputs.DOCKER_IMAGE_SEMVER }}-kctl${{ needs.prepare.outputs.KUBECTL_VERSION }}-kust${{ needs.prepare.outputs.KUSTOMIZE_VERSION }}-helm${{ needs.prepare.outputs.HELM_VERSION }}"
          LABELS="$LABELS,com.github.repo.branch=main"
          LABELS="$LABELS,com.github.repo.dockerfile=Dockerfile"
          echo "labels=${LABELS}" >> $GITHUB_OUTPUT

      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm64,linux/amd64
          push: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
          tags: ${{ steps.prep.outputs.tags }}
          labels: ${{ steps.prep.outputs.labels }}
          no-cache: false
          build-args: |
            KUBECTL_VERSION=${{ needs.prepare.outputs.KUBECTL_VERSION }}
            KUSTOMIZE_VERSION=${{ needs.prepare.outputs.KUSTOMIZE_VERSION }}
            HELM_VERSION=${{ needs.prepare.outputs.HELM_VERSION }}
      - name: Scan image
        uses: anchore/scan-action@v2
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
        with:
          image: "${{ needs.prepare.outputs.DOCKER_IMAGE }}:latest"
          fail-build: false
